# # ## POST ####
POST    http://localhost:4004/odata/v4/quiz/Quiz
Content-Type: application/json
x-qos:0

{
    "ID": "cf4450cf-3c56-4a81-b819-02bd7916f790",
    "title": "SAP BPA 200"
}

# POST Users###
# POST     http://localhost:4004/odata/v4/quiz/Users
# Content-Type: application/json
# x-qos:0

# {
#     "ID": "cf4450cf-3c56-4a81-b819-02bd7916f790",
#     "name": "Tejas",
#     "score": 100,
#     "resAnswer": {
#         "ID": "cf4450cf-3c56-4a81-b819-02bd7916f790",
#         "title": "SAP BPA Quiz 10",
#         "response": [{
#             "questions": "What is SAP BPA",
#             "answer": "Build Process Automation"
#         }]
#     }
# }


## POST Questions ##
# POST     http://localhost:4004/odata/v4/quiz/Questions
# Content-Type: application/json
# x-qos:0

# {
#         "ID": "cf4450cf-3c56-4a81-b819-02bd7916f7",
#         "quizID": "cf4450cf-3c56-4a81-b819-02bd7916f790",
#         "content": "Who are the key users of SAP BPA?",
#         "score": 10,
#         "answers":[{
#             "ID": "cf4450cf-3c56-4a81-b819-02bd7916f7001",
#             "questionID": "cf4450cf-3c56-4a81-b819-02bd7916f7",
#             "options": [
#                 {
#                 "option": "Citizen Developer",
#                 "correctOption": true
#                 },
#                 {
#                     "option":"Technical Developer",
#                     "correctOption": false
#                 }
#             ]
#         }]
# }